Fix type conversion for long in Windows system
ami-iit/matio-cpp pull request #63
Opened 2022-12-18 16:49 UTC by GiulioRomualdi

As discusses in https://github.com/ami-iit/bipedal-locomotion-framework/issues/579 the long in windows has a different size respect to the unix system indeed as explained here here https://learn.microsoft.com/en-us/cpp/cpp/data-type-ranges?view=msvc-170 and here https://www.ibm.com/docs/en/ibm-mq/8.0?topic=platforms-standard-data-types

The `long` is a strange type since
|     |   Unix 32bit |  Unix 64bit | Windows 64bit   | 
|:---:|:---:|:---:|:---:|
| `int` | 4 bytes | 4 bytes | 4 bytes | 
| `long` | 4 bytes | 8 bytes | 4 bytes | 

Without this fix, we have the compilation error presented in https://github.com/robotology/robotology-superbuild/issues/1307#issue-1463849212

I'm afraid we also have a similar error in macOS (see  https://github.com/robotology/robotology-superbuild/issues/1307#issue-1463849212). (This PR does not fix the problem for macOS)

This fixes https://github.com/ami-iit/bipedal-locomotion-framework/issues/579 and unlocks the possibility to compile the YarpRobotLoggerDevice on windows

2022-12-19 08:45 UTC, S-Dafarra commented
I remember having a similar issue with `size_t` in the past: https://github.com/ami-iit/matio-cpp/blob/e951ef357224501bc3ea77761d1b8900e4862cfa/include/matioCpp/ConversionUtilities.h#L50-L54 (relevant commit https://github.com/ami-iit/matio-cpp/pull/55/commits/3b622a7e413793121fa8d62dab211678b7997011)

2022-12-19 08:55 UTC, S-Dafarra requested changes
Also, could you add a test case like https://github.com/ami-iit/matio-cpp/blob/e951ef357224501bc3ea77761d1b8900e4862cfa/test/ElementUnitTest.cpp#L95-L97?

2022-12-19 08:55 UTC, S-Dafarra commented on include/matioCpp/ConversionUtilities.h
> +// In mcOS 64 bit a long has 8 bytes (8 byte = 64 bit)
```suggestion
// In macOS 64 bit a long has 8 bytes (8 byte = 64 bit)
```

2022-12-19 08:55 UTC, S-Dafarra commented on include/matioCpp/ConversionUtilities.h
> +
Could you restructure this code like the ``size_t`` case?

2024-05-14 09:32 UTC, GiulioRomualdi commented
Thanks to https://github.com/ami-iit/bipedal-locomotion-framework/pull/580 the PR is not required anymore. Let me know if you are interested in the feature otherwise we can close it without merging it

2024-05-14 15:49 UTC, S-Dafarra commented
Thanks @GiulioRomualdi, since there is an alternative fix, I would close this without merging.

2024-05-14 15:49 UTC, closed without merging